//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace База_артикулов.Модели
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllProductsInfoView
    {
        public int id { get; set; }
        public int idDescriptor { get; set; }
        public Nullable<int> idNorm { get; set; }
        public Nullable<int> idSubGroup { get; set; }
        public Nullable<int> idCover { get; set; }
        public Nullable<int> idMaterial { get; set; }
        public bool isInStock { get; set; }
        public Nullable<int> idPerforation { get; set; }
        public Nullable<int> idPackage { get; set; }
        public string code { get; set; }
        public string title { get; set; }
        public string titleShort { get; set; }
        public string description { get; set; }
        public int idDescriptorNorm { get; set; }
        public Nullable<int> idGroup { get; set; }
        public int idDescriptorSubGroups { get; set; }
        public Nullable<int> idLoadDiagram { get; set; }
        public Nullable<int> thickness { get; set; }
        public int idNormCovers { get; set; }
        public string typeMaterials { get; set; }
        public Nullable<int> idMaterialNorm { get; set; }
        public Nullable<int> idPrepackNorm { get; set; }
        public int idDescriptorPerforations { get; set; }
        public int idDescriptorPackages { get; set; }
        public int idDescriptorMaterials { get; set; }
        public int idDescriptorCovers { get; set; }
    }
}
