//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace База_артикулов.Модели
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllProductUnitsInfoView
    {
        public int id { get; set; }
        public int idProduct { get; set; }
        public Nullable<int> idUnit { get; set; }
        public Nullable<int> idType { get; set; }
        public double value { get; set; }
        public string titleUnitType { get; set; }
        public Nullable<int> OKEI { get; set; }
        public string titleUnit { get; set; }
        public string descriptionUnit { get; set; }
        public string titleShortUnit { get; set; }
    }
}
