//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace База_артикулов.Модели
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationsView
    {
        public int ID_применения { get; set; }
        public string Наименование_применения { get; set; }
        public Nullable<int> ID_направления { get; set; }
        public string Наименование_направления { get; set; }
        public Nullable<int> ID_схемы_нагрузки { get; set; }
        public string Наименование_схема_нагрузки { get; set; }
        public string URL_схемы_нагрузки { get; set; }
        public Nullable<int> ID_Файла_BIM_библиотеки { get; set; }
        public string Наименование_BIM_библиотеки { get; set; }
        public string URL_BIM_библиотеки { get; set; }
        public Nullable<int> ID_Файла_блоков_чертежей { get; set; }
        public string Наименование_файла_блоков_чертежей { get; set; }
        public string URL_блоков_чертежей { get; set; }
        public Nullable<int> ID_Альбома_типовых_узлов { get; set; }
        public string Наименование_альбома_типовых_узлов { get; set; }
        public string URL_альбома_типовых_узлов { get; set; }
    }
}
