//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace База_артикулов.Модели
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuisnessUnitsView
    {
        public int ID { get; set; }
        public string Дескриптор { get; set; }
        public Nullable<int> ID_Файла_BIM_библиотеки { get; set; }
        public Nullable<int> ID_Файла_блоков_чертежей { get; set; }
        public Nullable<int> ID_Типового_альбома { get; set; }
    }
}
