//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace База_артикулов.Модели
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuisnessUnits
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BuisnessUnits()
        {
            this.Applications = new HashSet<Applications>();
        }
    
        public int id { get; set; }
        public int idDescriptor { get; set; }
        public Nullable<int> idBimLibraryFile { get; set; }
        public Nullable<int> idDrawBlocksFile { get; set; }
        public Nullable<int> idTypicalAlbum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Applications> Applications { get; set; }
        public virtual Descriptors Descriptors { get; set; }
        public virtual Descriptors Descriptors1 { get; set; }
        public virtual Descriptors Descriptors2 { get; set; }
        public virtual Descriptors Descriptors3 { get; set; }
    }
}
