//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace База_артикулов.Модели
{
    using System;
    using System.Collections.Generic;
    
    public partial class DescriptorsViewDisplay
    {
        public int ID_дексриптора { get; set; }
        public string Наименование { get; set; }
        public string Сокращенное_наименование { get; set; }
        public string Код { get; set; }
        public string Описание { get; set; }
    }
}
