//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace База_артикулов.Модели
{
    using System;
    using System.Collections.Generic;
    
    public partial class DescriptorsResourcesView
    {
        public int ID_дескриптора_ресурса { get; set; }
        public string Наименование_объекта { get; set; }
        public string Наименование_ресурса { get; set; }
        public string Сокращенное_наименование_ресурса { get; set; }
        public string Отображаемое_название_ресурса { get; set; }
        public string Код_ресурса { get; set; }
        public string Описание_ресурса { get; set; }
        public string URL_ресурса { get; set; }
        public string Тип_ресурса { get; set; }
    }
}
