//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace База_артикулов.Модели
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fields
    {
        public int id { get; set; }
        public Nullable<int> idDescriptor { get; set; }
        public string titleRus { get; set; }
    
        public virtual Descriptors Descriptors { get; set; }
    }
}
