//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace База_артикулов.Модели
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupsView
    {
        public int ID_группы { get; set; }
        public string Наименование_группы { get; set; }
        public string Сокращенное_наименование_группы { get; set; }
        public string Код_группы { get; set; }
        public string URL_изображения_группы { get; set; }
        public Nullable<int> ID_класса { get; set; }
    }
}
