//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace База_артикулов.Модели
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialsView
    {
        public int ID_материала { get; set; }
        public string Наименование_материала { get; set; }
        public string Сокращенное_наименование_материала { get; set; }
        public string Обозначение_материала { get; set; }
        public string Обозначение_материала_марка_стали { get; set; }
        public string Стандарт_материала { get; set; }
        public string Код_стандарта_материала { get; set; }
        public string Стандарт_сырья { get; set; }
        public string Код_стандарта_сырья { get; set; }
    }
}
