//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace База_артикулов.Модели
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductUnitsView
    {
        public Nullable<int> ID_связи_продуктИзмерение { get; set; }
        public int ID_продукта { get; set; }
        public int ID_дескриптора_товара { get; set; }
        public Nullable<int> ID_единицы_измерения { get; set; }
        public string Наименование_единицы_измерения { get; set; }
        public string Сокращенное_наименование_единицы_измерения { get; set; }
        public Nullable<int> ID_типа_измерения { get; set; }
        public string Наименование_типа_единицы_измерения { get; set; }
        public Nullable<double> Значение { get; set; }
    }
}
