//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace База_артикулов.Модели
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsView
    {
        public int ID_продукта { get; set; }
        public string Артикул { get; set; }
        public string Наименование_продукта { get; set; }
        public string Сокращенное_наименование_продукта { get; set; }
        public string Описание_продукта { get; set; }
        public string Наименование_подгруппы { get; set; }
        public string Сокращенное_наименование_подгруппы { get; set; }
        public string Код_подгруппы { get; set; }
        public string URL_изображения_подгруппы { get; set; }
        public string Наименование_группы { get; set; }
        public string Сокращенное_наименование_группы { get; set; }
        public string Код_группы { get; set; }
        public string URL_изображения_группы { get; set; }
        public string Наименование_класса { get; set; }
        public string Сокращенное_наименование_класса { get; set; }
        public string Код_класса { get; set; }
        public string URL_изображения_класса { get; set; }
        public string Наименование_покрытия { get; set; }
        public string Название_стандарта { get; set; }
        public string Обозначение_покрытия { get; set; }
        public Nullable<int> Толщина_покрытия { get; set; }
    }
}
