//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace База_артикулов.Модели
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.ProductsAnalogs = new HashSet<ProductsAnalogs>();
            this.ProductsAnalogs1 = new HashSet<ProductsAnalogs>();
            this.ProductsVendorCodes = new HashSet<ProductsVendorCodes>();
            this.UnitsProducts = new HashSet<UnitsProducts>();
        }
    
        public int id { get; set; }
        public int idDescriptor { get; set; }
        public Nullable<int> idNorm { get; set; }
        public Nullable<int> idSubGroup { get; set; }
        public Nullable<int> idCover { get; set; }
        public Nullable<int> idMaterial { get; set; }
        public Nullable<int> idPerforation { get; set; }
        public Nullable<int> idPackage { get; set; }
        public bool isInStock { get; set; }
    
        public virtual Covers Covers { get; set; }
        public virtual Descriptors Descriptors { get; set; }
        public virtual Materials Materials { get; set; }
        public virtual Norms Norms { get; set; }
        public virtual Packages Packages { get; set; }
        public virtual Perforations Perforations { get; set; }
        public virtual SubGroups SubGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductsAnalogs> ProductsAnalogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductsAnalogs> ProductsAnalogs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductsVendorCodes> ProductsVendorCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UnitsProducts> UnitsProducts { get; set; }
    }
}
