//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace База_артикулов.Модели
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsAnalogs
    {
        public int id { get; set; }
        public Nullable<int> idOriginal { get; set; }
        public Nullable<int> idAnalog { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Products Products1 { get; set; }
    }
}
