//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace База_артикулов.Модели
{
    using System;
    using System.Collections.Generic;
    
    public partial class TablesView
    {
        public int TableId { get; set; }
        public string TableTitle { get; set; }
        public string TableTitleShort { get; set; }
        public string TableTitleDisplay { get; set; }
        public string TableDescription { get; set; }
    }
}
