//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace База_артикулов.Модели
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitsPerforations
    {
        public int id { get; set; }
        public int idPerforation { get; set; }
        public int idUnit { get; set; }
        public int idType { get; set; }
        public double Value { get; set; }
    
        public virtual Perforations Perforations { get; set; }
        public virtual Units Units { get; set; }
        public virtual UnitsTypes UnitsTypes { get; set; }
    }
}
