//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace База_артикулов.Модели
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitsPakages
    {
        public int id { get; set; }
        public int idPackage { get; set; }
        public Nullable<int> idUnit { get; set; }
        public Nullable<int> idType { get; set; }
        public Nullable<double> Value { get; set; }
    
        public virtual Packages Packages { get; set; }
        public virtual Units Units { get; set; }
        public virtual UnitsTypes UnitsTypes { get; set; }
    }
}
