//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace База_артикулов.Модели
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorCodesView
    {
        public int ID_артикула { get; set; }
        public Nullable<int> ID_продукта { get; set; }
        public string Артикул { get; set; }
        public bool Актуальность { get; set; }
        public bool Тип { get; set; }
        public Nullable<bool> Публичность { get; set; }
        public string Артикул_бухгалтерии { get; set; }
        public string Производитель { get; set; }
    }
}
