//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace База_артикулов.Модели
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewsView
    {
        public int ViewId { get; set; }
        public Nullable<int> ViewIdType { get; set; }
        public string ViewTypeTitle { get; set; }
        public string ViewTypeTitleShort { get; set; }
        public string ViewTitle { get; set; }
        public string ViewTitleShort { get; set; }
        public string ViewTitleDisplay { get; set; }
        public string ViewDescription { get; set; }
    }
}
