//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace База_артикулов.Модели
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewTypesView
    {
        public int id { get; set; }
        public string DescriptorTitle { get; set; }
        public string DescriptorTitleShort { get; set; }
        public string DescriptorTitleDisplay { get; set; }
        public string DescriptorDescription { get; set; }
    }
}
