//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace База_артикулов.Модели
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewsTablesView
    {
        public int ID { get; set; }
        public int ID_дескриптора_представления { get; set; }
        public string Наименование_представления { get; set; }
        public string Сокращенное_наименование_представления { get; set; }
        public string Отображаемое_название_представления { get; set; }
        public string Тип { get; set; }
        public int ID_дескриптора_таблицы { get; set; }
        public string Наименование_таблицы { get; set; }
        public string Сокращенное_наименование_таблицы { get; set; }
        public string Отображаемое_название_таблицы { get; set; }
    }
}
