//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace База_артикулов.Модели
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewsTables
    {
        public int id { get; set; }
        public Nullable<int> idTable { get; set; }
        public Nullable<int> idView { get; set; }
    
        public virtual Tables Tables { get; set; }
        public virtual Views Views { get; set; }
    }
}
